import React, { useEffect, useState } from 'react';
import { Activity, ChevronLeft, ChevronRight, RefreshCw, Search } from 'lucide-react';
import { api } from '../../services/api';
import type { AdminActivityResponse, AdminReportOptions } from '../../types';

const field='h-11 rounded-xl border border-slate-700 bg-[#080D18] px-3 text-sm text-slate-200 outline-none focus:border-cyan-400';
const eventColor=(event:string)=>event.includes('COMPLETED')||event==='FLAG_CAPTURED'?'text-emerald-300 bg-emerald-400/10':event.startsWith('ADMIN_')?'text-violet-300 bg-violet-400/10':event.includes('HINT')?'text-amber-300 bg-amber-400/10':'text-cyan-300 bg-cyan-400/10';

export const AdminActivityPage:React.FC=()=>{
  const [options,setOptions]=useState<AdminReportOptions|null>(null);
  const [data,setData]=useState<AdminActivityResponse|null>(null);
  const [filters,setFilters]=useState({search:'',eventType:'',userId:'',from:'',to:'',page:1,pageSize:20});
  const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async(next=filters)=>{setLoading(true);setError('');try{const [logs,choices]=await Promise.all([api.getAdminActivity(next),options?Promise.resolve(options):api.getAdminReportOptions()]);setData(logs);setOptions(choices);}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const apply=()=>{const next={...filters,page:1};setFilters(next);void load(next);};
  const go=(page:number)=>{const next={...filters,page};setFilters(next);void load(next);};
  return <div className="space-y-6"><header className="rounded-[24px] border border-violet-400/20 bg-gradient-to-br from-[#111C31] to-[#171229] p-6 sm:p-8"><div className="flex items-center gap-3 text-violet-300"><Activity className="h-6 w-6"/><span className="text-xs font-black tracking-[.2em]">AUDIT TRAIL</span></div><h1 className="mt-3 text-2xl font-black sm:text-3xl">บันทึกกิจกรรม</h1><p className="mt-2 text-sm text-slate-400">ตรวจสอบเหตุการณ์ของผู้เรียนและผู้ดูแล โดยซ่อนข้อมูลที่ละเอียดอ่อน</p></header>
  <section className="rounded-[20px] border border-slate-700/70 bg-[#111827]/90 p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="relative xl:col-span-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-500"/><input className={`${field} w-full pl-9`} placeholder="ค้นหา User, Event, Entity" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} onKeyDown={e=>e.key==='Enter'&&apply()}/></label><select className={field} value={filters.eventType} onChange={e=>setFilters({...filters,eventType:e.target.value})}><option value="">ทุก Event</option>{options?.eventTypes.map(x=><option key={x}>{x}</option>)}</select><select className={field} value={filters.userId} onChange={e=>setFilters({...filters,userId:e.target.value})}><option value="">ทุก User</option>{options?.users.map(x=><option key={x.id} value={x.id}>{x.username}</option>)}</select><input className={field} type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input className={field} type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></div><div className="mt-4 flex items-center gap-3"><button onClick={apply} className="rounded-xl bg-gradient-to-r from-cyan-400 to-blue-500 px-5 py-2.5 text-sm font-black text-slate-950">ใช้ตัวกรอง</button><button onClick={()=>void load()} className="rounded-xl border border-slate-700 p-2.5 text-slate-300" aria-label="รีเฟรช"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button>{data&&<span className="ml-auto text-xs text-slate-500">ทั้งหมด {data.pagination.total} รายการ</span>}</div>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}</section>
  <section className="overflow-hidden rounded-[20px] border border-slate-700/70 bg-[#111827]/90"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr className="border-b border-slate-700 bg-slate-900/70 text-xs uppercase tracking-wider text-slate-500"><th className="p-4">Time</th><th className="p-4">User</th><th className="p-4">Event</th><th className="p-4">Entity</th><th className="p-4">Details</th></tr></thead><tbody>{data?.logs.length?data.logs.map(log=><tr key={log.id} className="border-b border-slate-800 align-top hover:bg-cyan-400/[.025]"><td className="whitespace-nowrap p-4 font-mono text-xs text-slate-400">{new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(log.time))}</td><td className="p-4 font-bold">{log.username??'System'}</td><td className="p-4"><span className={`inline-flex rounded-lg px-2.5 py-1 font-mono text-xs font-bold ${eventColor(log.eventType)}`}>{log.eventType}</span></td><td className="p-4"><p className="font-medium">{log.entity??'—'}</p>{log.entityType&&<p className="mt-1 font-mono text-[11px] text-slate-500">{log.entityType} #{log.entityId}</p>}</td><td className="p-4 text-xs text-slate-400">{log.details&&Object.keys(log.details).length?Object.entries(log.details).map(([k,v])=><span key={k} className="mr-2 inline-block rounded bg-slate-800 px-2 py-1"><b className="text-slate-500">{k}:</b> {String(v)}</span>):'—'}</td></tr>):<tr><td colSpan={5} className="py-16 text-center text-slate-500">ไม่พบบันทึกกิจกรรมตามตัวกรอง</td></tr>}</tbody></table></div>{data&&<footer className="flex items-center justify-between border-t border-slate-700 p-4"><span className="text-xs text-slate-500">หน้า {data.pagination.page} จาก {data.pagination.totalPages}</span><div className="flex gap-2"><button disabled={data.pagination.page<=1||loading} onClick={()=>go(data.pagination.page-1)} className="rounded-lg border border-slate-700 p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4"/></button><button disabled={data.pagination.page>=data.pagination.totalPages||loading} onClick={()=>go(data.pagination.page+1)} className="rounded-lg border border-slate-700 p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4"/></button></div></footer>}</section></div>;
};
