import React, { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, BookOpenCheck, GitBranch, Plus, Save, Trash2, Unlink } from 'lucide-react';
import { AdminConfirmationModal } from '../../components/admin/AdminConfirmationModal';
import { api } from '../../services/api';
import type { AdminLearningPath, AdminLearningPathStage, AdminLearningPathsResponse } from '../../types';

const icons: AdminLearningPathStage['icon'][] = ['Network', 'Terminal', 'Route', 'AlertTriangle'];
const accents = ['#22D3EE', '#3B82F6', '#8B5CF6', '#EC4899', '#F59E0B', '#10B981'];

const StageEditor: React.FC<{ path: AdminLearningPath; stage: AdminLearningPathStage; unassigned: AdminLearningPathsResponse['unassignedMissions']; reload: () => Promise<void>; confirm: (value: { title: string; description: string; action: () => Promise<void> }) => void; }> = ({ path, stage, unassigned, reload, confirm }) => {
  const [form, setForm] = useState({ name: stage.name, description: stage.description, icon: stage.icon, accent: stage.accent });
  const [missionId, setMissionId] = useState('');
  useEffect(() => setForm({ name: stage.name, description: stage.description, icon: stage.icon, accent: stage.accent }), [stage]);
  return <article className="rounded-2xl border border-slate-700/70 bg-slate-950/55 p-4" style={{ borderLeftColor: stage.accent, borderLeftWidth: 3 }}>
    <div className="grid gap-3 lg:grid-cols-[1fr_1.5fr_130px_100px_auto]"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="h-10 rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm font-bold outline-none focus:border-cyan-400" /><input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="h-10 rounded-xl border border-slate-700 bg-slate-900 px-3 text-xs outline-none focus:border-cyan-400" /><select value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value as AdminLearningPathStage['icon'] })} className="rounded-xl border border-slate-700 bg-slate-900 px-2 text-xs">{icons.map((icon) => <option key={icon}>{icon}</option>)}</select><select value={form.accent} onChange={(e) => setForm({ ...form, accent: e.target.value })} className="rounded-xl border border-slate-700 bg-slate-900 px-2 text-xs">{accents.map((accent) => <option key={accent}>{accent}</option>)}</select><button onClick={async () => { await api.updateAdminLearningPathStage(path.id, stage.id, form); await reload(); }} className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400 text-slate-950"><Save className="h-4 w-4" /></button></div>
    <div className="mt-3 flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] text-slate-500">STAGE {stage.orderIndex}</span><button onClick={async () => { await api.reorderAdminLearningPathStage(path.id, stage.id, 'up'); await reload(); }} className="rounded-lg border border-slate-700 p-1.5 text-slate-400"><ArrowUp className="h-3.5 w-3.5" /></button><button onClick={async () => { await api.reorderAdminLearningPathStage(path.id, stage.id, 'down'); await reload(); }} className="rounded-lg border border-slate-700 p-1.5 text-slate-400"><ArrowDown className="h-3.5 w-3.5" /></button><label className="ml-auto flex items-center gap-2 text-[11px] text-slate-400">เงื่อนไขก่อนเข้า<select value={stage.prerequisiteStageId || ''} onChange={async (e) => { await api.setAdminStagePrerequisite(path.id, stage.id, e.target.value ? Number(e.target.value) : null); await reload(); }} className="h-9 rounded-xl border border-slate-700 bg-slate-900 px-2"><option value="">ไม่มี</option>{path.stages.filter((item) => item.id !== stage.id).map((item) => <option key={item.id} value={item.id}>{item.orderIndex}. {item.name}</option>)}</select></label><button onClick={() => confirm({ title: 'ลบด่านนี้?', description: 'Mission ภายในด่านจะถูกยกเลิกการเชื่อม แต่จะไม่ถูกลบออกจากระบบ', action: async () => { await api.deleteAdminLearningPathStage(path.id, stage.id); await reload(); } })} className="rounded-lg border border-red-300/20 p-2 text-red-300"><Trash2 className="h-3.5 w-3.5" /></button></div>
    <div className="mt-4 space-y-2">{stage.missions.map((mission) => <div key={mission.id} className="flex items-center gap-2 rounded-xl border border-slate-800 bg-slate-900/70 px-3 py-2"><span className="w-8 font-mono text-[10px] text-cyan-300">#{String(mission.missionNumber).padStart(2, '0')}</span><span className="min-w-0 flex-1 truncate text-xs font-bold text-slate-300">{mission.title}</span><button onClick={async () => { await api.reorderAdminStageMission(path.id, stage.id, mission.id, 'up'); await reload(); }} className="text-slate-500 hover:text-cyan-300"><ArrowUp className="h-3.5 w-3.5" /></button><button onClick={async () => { await api.reorderAdminStageMission(path.id, stage.id, mission.id, 'down'); await reload(); }} className="text-slate-500 hover:text-cyan-300"><ArrowDown className="h-3.5 w-3.5" /></button><button onClick={async () => { await api.unassignMissionFromStage(path.id, stage.id, mission.id); await reload(); }} title="ยกเลิกการเชื่อม" className="text-red-300"><Unlink className="h-3.5 w-3.5" /></button></div>)}</div>
    <div className="mt-3 flex gap-2"><select value={missionId} onChange={(e) => setMissionId(e.target.value)} className="h-9 min-w-0 flex-1 rounded-xl border border-dashed border-slate-700 bg-slate-900 px-3 text-xs"><option value="">เลือก Mission ที่ยังไม่ถูกจัดด่าน</option>{unassigned.map((mission) => <option key={mission.id} value={mission.id}>#{mission.missionNumber} — {mission.title}</option>)}</select><button disabled={!missionId} onClick={async () => { await api.assignMissionToStage(path.id, stage.id, Number(missionId)); setMissionId(''); await reload(); }} className="rounded-xl border border-emerald-300/20 bg-emerald-400/10 px-3 text-xs font-bold text-emerald-300 disabled:opacity-30">เชื่อม Mission</button></div>
  </article>;
};

export const AdminLearningPathsPage: React.FC = () => {
  const [data, setData] = useState<AdminLearningPathsResponse | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [newPath, setNewPath] = useState({ name: '', description: '', status: 'draft' as 'draft' | 'published' });
  const [newStage, setNewStage] = useState<Record<number, { name: string; description: string }>>({});
  const [confirmValue, setConfirmValue] = useState<{ title: string; description: string; action: () => Promise<void> } | null>(null);
  const load = async () => { try { setData(await api.getAdminLearningPaths()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'โหลดข้อมูลไม่สำเร็จ'); } };
  useEffect(() => { void load(); }, []);
  const updatePath = async (path: AdminLearningPath) => { await api.updateAdminLearningPath(path.id, { name: path.name, slug: path.slug, description: path.description, status: path.status }); await load(); };
  const mutatePath = (pathId: number, change: Partial<AdminLearningPath>) => setData((current) => current ? { ...current, paths: current.paths.map((path) => path.id === pathId ? { ...path, ...change } : path) } : current);

  return <div className="space-y-5 pb-8"><section className="rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-slate-800 to-slate-950 p-6 shadow-2xl sm:p-8"><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">LEARNING PATH MANAGEMENT</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">จัดการเส้นทางการเรียนรู้</h1><p className="mt-2 text-sm text-slate-400">จัดด่าน เชื่อม Mission กำหนดลำดับ และตั้งเงื่อนไขก่อนเข้าแบบง่าย</p></section>{(error || notice) && <div className={`rounded-2xl border p-3 text-sm ${error ? 'border-red-300/20 bg-red-400/10 text-red-300' : 'border-emerald-300/20 bg-emerald-400/10 text-emerald-300'}`}>{error || notice}</div>}
    <form onSubmit={async (e) => { e.preventDefault(); setError(''); try { await api.createAdminLearningPath(newPath); setNewPath({ name: '', description: '', status: 'draft' }); setNotice('สร้าง Learning Path แล้ว'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'สร้างไม่สำเร็จ'); } }} className="grid gap-3 rounded-3xl border border-slate-700 bg-slate-900/60 p-5 lg:grid-cols-[1fr_2fr_150px_auto]"><input required value={newPath.name} onChange={(e) => setNewPath({ ...newPath, name: e.target.value })} placeholder="ชื่อ Learning Path" className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /><input required value={newPath.description} onChange={(e) => setNewPath({ ...newPath, description: e.target.value })} placeholder="คำอธิบาย" className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /><select value={newPath.status} onChange={(e) => setNewPath({ ...newPath, status: e.target.value as 'draft' | 'published' })} className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm"><option value="draft">Draft</option><option value="published">Published</option></select><button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-5 text-sm font-black text-slate-950"><Plus className="h-4 w-4" />สร้าง Path</button></form>
    {data?.paths.map((path) => <section key={path.id} className="rounded-3xl border border-slate-700/70 bg-slate-900/60 p-5 shadow-xl"><div className="grid gap-3 lg:grid-cols-[1fr_2fr_140px_auto]"><input value={path.name} onChange={(e) => mutatePath(path.id, { name: e.target.value })} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 font-bold" /><input value={path.description} onChange={(e) => mutatePath(path.id, { description: e.target.value })} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /><select value={path.status} onChange={(e) => mutatePath(path.id, { status: e.target.value as 'draft' | 'published' })} className="rounded-xl border border-slate-700 bg-slate-950 px-3"><option value="draft">Draft</option><option value="published">Published</option></select><div className="flex gap-2"><button onClick={() => void updatePath(path)} className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-400 text-slate-950"><Save className="h-4 w-4" /></button><button onClick={async () => { await api.setAdminLearningPathStatus(path.id, path.status === 'published' ? 'draft' : 'published'); await load(); }} title="Publish/Unpublish" className="grid h-11 w-11 place-items-center rounded-xl border border-cyan-300/20 text-cyan-300"><BookOpenCheck className="h-4 w-4" /></button><button onClick={() => setConfirmValue({ title: 'ลบ Learning Path?', description: 'ด่านจะถูกลบและ Mission จะกลับไปอยู่ในรายการที่ยังไม่จัดด่าน โดยตัว Mission จะไม่ถูกลบ', action: async () => { await api.deleteAdminLearningPath(path.id); await load(); } })} className="grid h-11 w-11 place-items-center rounded-xl border border-red-300/20 text-red-300"><Trash2 className="h-4 w-4" /></button></div></div><p className="mt-2 font-mono text-[10px] text-slate-600">/{path.slug} · {path.stages.length} stages</p>
      <div className="mt-5 space-y-4">{path.stages.map((stage) => <StageEditor key={stage.id} path={path} stage={stage} unassigned={data.unassignedMissions} reload={load} confirm={setConfirmValue} />)}</div>
      <div className="mt-4 flex gap-2 rounded-2xl border border-dashed border-slate-700 p-3"><GitBranch className="mt-2 h-4 w-4 text-violet-300" /><input value={newStage[path.id]?.name || ''} onChange={(e) => setNewStage({ ...newStage, [path.id]: { name: e.target.value, description: newStage[path.id]?.description || '' } })} placeholder="ชื่อด่านใหม่" className="h-9 min-w-0 flex-1 rounded-xl bg-slate-950 px-3 text-xs" /><input value={newStage[path.id]?.description || ''} onChange={(e) => setNewStage({ ...newStage, [path.id]: { name: newStage[path.id]?.name || '', description: e.target.value } })} placeholder="คำอธิบาย" className="h-9 min-w-0 flex-[2] rounded-xl bg-slate-950 px-3 text-xs" /><button disabled={!newStage[path.id]?.name} onClick={async () => { await api.createAdminLearningPathStage(path.id, { name: newStage[path.id].name, description: newStage[path.id].description, icon: 'Network', accent: '#22D3EE' }); setNewStage({ ...newStage, [path.id]: { name: '', description: '' } }); await load(); }} className="rounded-xl bg-violet-500 px-4 text-xs font-bold disabled:opacity-30">เพิ่มด่าน</button></div>
    </section>)}
    <AdminConfirmationModal open={Boolean(confirmValue)} title={confirmValue?.title || ''} description={confirmValue?.description || ''} confirmLabel="ยืนยัน" destructive onClose={() => setConfirmValue(null)} onConfirm={confirmValue?.action || (async () => undefined)} />
  </div>;
};
