import React, { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, BarChart3, CheckCircle2, ClipboardCheck, Edit3, Plus, Save, Trash2, Users } from 'lucide-react';
import { AdminConfirmationModal } from '../../components/admin/AdminConfirmationModal';
import { api } from '../../services/api';
import type { AdminAssessment, AdminAssessmentMetrics, AdminAssessmentQuestion, AdminAssessmentResult } from '../../types';

const emptyQuestion = { category: 'IP Addressing' as AdminAssessmentQuestion['category'], question: '', optionA: '', optionB: '', optionC: '', optionD: '', correctAnswer: 'A' as const, explanation: '' };
const categories: AdminAssessmentQuestion['category'][] = ['IP Addressing', 'Subnetting', 'VLAN', 'Routing', 'Troubleshooting'];
const metric = (value: number | null, suffix = '%') => value === null ? '—' : `${value}${suffix}`;

export const AdminAssessmentsPage: React.FC = () => {
  const [tab, setTab] = useState<'content' | 'results'>('content'); const [assessments, setAssessments] = useState<AdminAssessment[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null); const [questions, setQuestions] = useState<AdminAssessmentQuestion[]>([]);
  const [questionForm, setQuestionForm] = useState(emptyQuestion); const [editingQuestionId, setEditingQuestionId] = useState<number | null>(null);
  const [newAssessment, setNewAssessment] = useState({ title: '', description: '', assessmentType: 'pretest' as 'pretest' | 'posttest', isActive: false });
  const [results, setResults] = useState<AdminAssessmentResult[]>([]); const [metrics, setMetrics] = useState<AdminAssessmentMetrics | null>(null); const [resultType, setResultType] = useState('all');
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [deleteQuestion, setDeleteQuestion] = useState<AdminAssessmentQuestion | null>(null);

  const loadAssessments = async () => { try { const data = await api.getAdminAssessments(); setAssessments(data.assessments); setSelectedId((current) => current || data.assessments[0]?.id || null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'โหลด Assessment ไม่สำเร็จ'); } };
  const loadQuestions = async (id: number) => { try { setQuestions((await api.getAdminAssessmentQuestions(id)).questions); } catch (cause) { setError(cause instanceof Error ? cause.message : 'โหลดคำถามไม่สำเร็จ'); } };
  const loadResults = async () => { try { const [resultData, metricData] = await Promise.all([api.getAdminAssessmentResults(resultType), api.getAdminAssessmentMetrics()]); setResults(resultData.results); setMetrics(metricData.metrics); } catch (cause) { setError(cause instanceof Error ? cause.message : 'โหลดผลประเมินไม่สำเร็จ'); } };
  useEffect(() => { void loadAssessments(); }, []); useEffect(() => { if (selectedId) void loadQuestions(selectedId); }, [selectedId]); useEffect(() => { if (tab === 'results') void loadResults(); }, [tab, resultType]);
  const mutateAssessment = (id: number, change: Partial<AdminAssessment>) => setAssessments((items) => items.map((item) => item.id === id ? { ...item, ...change } : item));
  const saveAssessment = async (item: AdminAssessment) => { setError(''); try { await api.updateAdminAssessment(item.id, { title: item.title, slug: item.slug, description: item.description, assessmentType: item.assessmentType, isActive: Boolean(item.isActive) }); setNotice('บันทึก Assessment แล้ว'); await loadAssessments(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'บันทึกไม่สำเร็จ'); } };
  const submitQuestion = async (event: React.FormEvent) => { event.preventDefault(); if (!selectedId) return; setError(''); try { if (editingQuestionId) await api.updateAdminAssessmentQuestion(selectedId, editingQuestionId, questionForm); else await api.createAdminAssessmentQuestion(selectedId, questionForm); setQuestionForm(emptyQuestion); setEditingQuestionId(null); setNotice(editingQuestionId ? 'แก้ไขคำถามแล้ว' : 'เพิ่มคำถามแล้ว'); await loadQuestions(selectedId); await loadAssessments(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'บันทึกคำถามไม่สำเร็จ'); } };

  return <div className="space-y-5 pb-8"><section className="rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 p-6 shadow-2xl sm:p-8"><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">PRE-TEST / POST-TEST MANAGEMENT</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">จัดการแบบทดสอบก่อนและหลังเรียน</h1><p className="mt-2 text-sm text-slate-400">บริหารชุดคำถาม เฉลย ลำดับ และตรวจสอบผลการเรียนรู้จากข้อมูลจริง</p></section>
    <div className="flex gap-2 rounded-2xl border border-slate-700 bg-slate-900/60 p-2"><button onClick={() => setTab('content')} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold ${tab === 'content' ? 'bg-cyan-400 text-slate-950' : 'text-slate-400'}`}><ClipboardCheck className="mr-2 inline h-4 w-4" />จัดการ Assessment</button><button onClick={() => setTab('results')} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold ${tab === 'results' ? 'bg-violet-500 text-white' : 'text-slate-400'}`}><BarChart3 className="mr-2 inline h-4 w-4" />ผลการประเมิน</button></div>
    {(error || notice) && <div className={`rounded-2xl border p-3 text-sm ${error ? 'border-red-300/20 bg-red-400/10 text-red-300' : 'border-emerald-300/20 bg-emerald-400/10 text-emerald-300'}`}>{error || notice}</div>}

    {tab === 'content' && <><form onSubmit={async (event) => { event.preventDefault(); try { const created = await api.createAdminAssessment(newAssessment); setNewAssessment({ title: '', description: '', assessmentType: 'pretest', isActive: false }); setSelectedId(created.assessment.id); setNotice('สร้าง Assessment แล้ว'); await loadAssessments(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'สร้างไม่สำเร็จ'); } }} className="grid gap-3 rounded-3xl border border-slate-700 bg-slate-900/60 p-5 lg:grid-cols-[1fr_1.7fr_140px_auto]"><input required value={newAssessment.title} onChange={(e) => setNewAssessment({ ...newAssessment, title: e.target.value })} placeholder="ชื่อ Assessment" className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /><input required value={newAssessment.description} onChange={(e) => setNewAssessment({ ...newAssessment, description: e.target.value })} placeholder="คำอธิบาย" className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /><select value={newAssessment.assessmentType} onChange={(e) => setNewAssessment({ ...newAssessment, assessmentType: e.target.value as 'pretest' | 'posttest' })} className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm"><option value="pretest">PRE-TEST</option><option value="posttest">POST-TEST</option></select><button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-4 text-sm font-black text-slate-950"><Plus className="h-4 w-4" />สร้าง</button></form>
      <section className="grid gap-4 xl:grid-cols-2">{assessments.map((item) => <article key={item.id} onClick={() => setSelectedId(item.id)} className={`cursor-pointer rounded-3xl border p-5 ${selectedId === item.id ? 'border-cyan-300/50 bg-cyan-400/[.06]' : 'border-slate-700 bg-slate-900/60'}`}><div className="flex items-center justify-between gap-3"><span className={`rounded-full px-2.5 py-1 font-mono text-[10px] font-bold ${item.assessmentType === 'pretest' ? 'bg-cyan-400/10 text-cyan-300' : 'bg-violet-400/10 text-violet-300'}`}>{item.assessmentType.toUpperCase()}</span><label onClick={(e) => e.stopPropagation()} className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={Boolean(item.isActive)} onChange={async (e) => { await api.setAdminAssessmentActive(item.id, e.target.checked); await loadAssessments(); }} />เปิดใช้งาน</label></div><input value={item.title} onChange={(e) => mutateAssessment(item.id, { title: e.target.value })} onClick={(e) => e.stopPropagation()} className="mt-3 h-10 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 font-bold" /><input value={item.description} onChange={(e) => mutateAssessment(item.id, { description: e.target.value })} onClick={(e) => e.stopPropagation()} className="mt-2 h-10 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 text-xs" /><div className="mt-4 flex items-center justify-between border-t border-slate-800 pt-3"><span className="text-xs text-slate-500">{item.questionCount} คำถาม · {item.resultCount} ผลลัพธ์</span><button onClick={(e) => { e.stopPropagation(); void saveAssessment(item); }} className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-400 text-slate-950"><Save className="h-4 w-4" /></button></div></article>)}</section>
      {selectedId && <section className="rounded-3xl border border-slate-700 bg-slate-900/60 p-5"><h2 className="text-lg font-black">Question Management</h2><form onSubmit={(event) => void submitQuestion(event)} className="mt-4 grid gap-3"><div className="grid gap-3 lg:grid-cols-[180px_1fr]"><select value={questionForm.category} onChange={(e) => setQuestionForm({ ...questionForm, category: e.target.value as AdminAssessmentQuestion['category'] })} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm">{categories.map((category) => <option key={category}>{category}</option>)}</select><input required value={questionForm.question} onChange={(e) => setQuestionForm({ ...questionForm, question: e.target.value })} placeholder="คำถาม" className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /></div><div className="grid gap-2 md:grid-cols-2">{(['A', 'B', 'C', 'D'] as const).map((letter) => <label key={letter} className="flex items-center gap-2"><input type="radio" name="correct-answer" checked={questionForm.correctAnswer === letter} onChange={() => setQuestionForm({ ...questionForm, correctAnswer: letter })} /><span className="font-mono text-xs font-bold text-cyan-300">{letter}</span><input required value={questionForm[`option${letter}`]} onChange={(e) => setQuestionForm({ ...questionForm, [`option${letter}`]: e.target.value })} placeholder={`ตัวเลือก ${letter}`} className="h-10 min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 text-xs" /></label>)}</div><div className="flex gap-2"><input required value={questionForm.explanation} onChange={(e) => setQuestionForm({ ...questionForm, explanation: e.target.value })} placeholder="คำอธิบายเฉลย" className="h-10 min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 text-xs" /><button className="rounded-xl bg-violet-500 px-4 text-xs font-bold">{editingQuestionId ? 'บันทึกการแก้ไข' : 'เพิ่มคำถาม'}</button>{editingQuestionId && <button type="button" onClick={() => { setEditingQuestionId(null); setQuestionForm(emptyQuestion); }} className="rounded-xl border border-slate-700 px-4 text-xs">ยกเลิก</button>}</div></form>
        <div className="mt-5 space-y-2">{questions.map((question, index) => <div key={question.id} className="flex items-center gap-2 rounded-2xl border border-slate-800 bg-slate-950/60 p-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-800 font-mono text-xs text-cyan-300">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-300">{question.question}</p><p className="mt-1 text-[10px] text-slate-500">{question.category} · คำตอบที่ถูก: <strong className="text-emerald-300">{question.correctAnswer}</strong></p></div><button onClick={async () => { await api.reorderAdminAssessmentQuestion(selectedId, question.id, 'up'); await loadQuestions(selectedId); }} className="text-slate-500"><ArrowUp className="h-4 w-4" /></button><button onClick={async () => { await api.reorderAdminAssessmentQuestion(selectedId, question.id, 'down'); await loadQuestions(selectedId); }} className="text-slate-500"><ArrowDown className="h-4 w-4" /></button><button onClick={() => { setEditingQuestionId(question.id); setQuestionForm({ category: question.category, question: question.question, optionA: question.optionA, optionB: question.optionB, optionC: question.optionC, optionD: question.optionD, correctAnswer: question.correctAnswer, explanation: question.explanation }); }} className="text-cyan-300"><Edit3 className="h-4 w-4" /></button><button onClick={() => setDeleteQuestion(question)} className="text-red-300"><Trash2 className="h-4 w-4" /></button></div>)}</div>
      </section>}</>}

    {tab === 'results' && <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Average Pre-Test", metric(metrics?.averagePreTest ?? null), 'text-cyan-300'], ['Average Post-Test', metric(metrics?.averagePostTest ?? null), 'text-violet-300'], ['Average Improvement', metrics?.averageImprovement == null ? '—' : `${metrics.averageImprovement > 0 ? '+' : ''}${metrics.averageImprovement} pp`, 'text-emerald-300'], ['Participants', String(metrics?.numberOfParticipants ?? 0), 'text-amber-300']].map(([label, value, color]) => <article key={label} className="rounded-3xl border border-slate-700 bg-slate-900/60 p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className={`mt-2 font-mono text-2xl font-black ${color}`}>{value}</p></article>)}</section><section className="overflow-hidden rounded-3xl border border-slate-700 bg-slate-900/60"><div className="flex items-center justify-between border-b border-slate-700 p-5"><div><h2 className="font-black">ผลการประเมินรายบุคคล</h2><p className="mt-1 text-xs text-slate-500">Improvement ใช้ผลล่าสุดของ PRE-TEST และ POST-TEST ต่อผู้เรียน</p></div><select value={resultType} onChange={(e) => setResultType(e.target.value)} className="h-10 rounded-xl border border-slate-700 bg-slate-950 px-3 text-xs"><option value="all">ทั้งหมด</option><option value="pretest">PRE-TEST</option><option value="posttest">POST-TEST</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-950/60 text-[10px] uppercase text-slate-500"><tr><th className="px-5 py-4">Username</th><th className="px-4 py-4">Assessment Type</th><th className="px-4 py-4">Score</th><th className="px-4 py-4">Percentage</th><th className="px-5 py-4">Completed At</th></tr></thead><tbody className="divide-y divide-slate-800">{results.map((result) => <tr key={result.id}><td className="px-5 py-4 text-sm font-bold text-slate-300"><Users className="mr-2 inline h-4 w-4 text-cyan-300" />{result.username}</td><td className="px-4 py-4 font-mono text-xs text-violet-300">{result.assessmentType.toUpperCase()}</td><td className="px-4 py-4 font-mono text-xs">{result.correctAnswers}/{result.totalQuestions}</td><td className="px-4 py-4 font-mono text-sm font-black text-emerald-300">{result.percentage}%</td><td className="px-5 py-4 text-xs text-slate-400">{new Intl.DateTimeFormat('th-TH', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(result.completedAt))}</td></tr>)}</tbody></table></div>{results.length === 0 && <p className="p-10 text-center text-sm text-slate-500">ยังไม่มีผลการประเมิน</p>}</section><div className="flex items-center gap-2 rounded-2xl border border-emerald-300/15 bg-emerald-400/[.05] p-4 text-xs text-slate-400"><CheckCircle2 className="h-5 w-5 text-emerald-300" />Average Improvement คำนวณเฉพาะผู้เรียนที่มีผลล่าสุดครบทั้ง PRE-TEST และ POST-TEST ({metrics?.pairedParticipants || 0} คน)</div></>}
    <AdminConfirmationModal open={Boolean(deleteQuestion)} title="ลบคำถาม?" description="คำถามจะถูกนำออกจาก Assessment นี้ ผลการประเมินเดิมจะยังคงอยู่" confirmLabel="ลบคำถาม" destructive onClose={() => setDeleteQuestion(null)} onConfirm={async () => { if (!selectedId || !deleteQuestion) return; await api.deleteAdminAssessmentQuestion(selectedId, deleteQuestion.id); await loadQuestions(selectedId); await loadAssessments(); }} />
  </div>;
};
