import React, { useEffect, useState } from 'react';
import { Award, Plus, Save, ShieldCheck, Sparkles, Trash2 } from 'lucide-react';
import { AdminConfirmationModal } from '../../components/admin/AdminConfirmationModal';
import { api } from '../../services/api';
import type { AdminAchievement } from '../../types';

const iconOptions = ['Cable', 'ShieldAlert', 'Route', 'Network', 'Zap', 'Award', 'Binary', 'Terminal', 'Trophy', 'Star'];
const conditionLabels: Record<string, string> = {
  mission_count: 'จำนวน Mission ที่สำเร็จ', category_routing: 'Mission หมวด Routing', category_vlan: 'Mission หมวด VLAN',
  category_ip_addressing: 'Mission หมวด IP Addressing', no_hint_completion: 'สำเร็จโดยไม่ใช้ Hint', perfect_score_count: 'Mission คะแนนเต็ม',
  packet_tracer_download_count: 'จำนวนดาวน์โหลด Packet Tracer', xp_total: 'XP รวม',
};

export const AdminAchievementsPage: React.FC = () => {
  const [items, setItems] = useState<AdminAchievement[]>([]); const [conditionTypes, setConditionTypes] = useState<string[]>([]);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [deleteTarget, setDeleteTarget] = useState<AdminAchievement | null>(null);
  const [form, setForm] = useState({ name: '', description: '', icon: 'Award', conditionType: 'mission_count', conditionValue: 1, isActive: true });
  const load = async () => { try { const result = await api.getAdminAchievements(); setItems(result.achievements); setConditionTypes(result.conditionTypes); } catch (cause) { setError(cause instanceof Error ? cause.message : 'โหลด Achievement ไม่สำเร็จ'); } };
  useEffect(() => { void load(); }, []);
  const mutate = (id: number, values: Partial<AdminAchievement>) => setItems((current) => current.map((item) => item.id === id ? { ...item, ...values } : item));
  const save = async (item: AdminAchievement) => { setError(''); try { await api.updateAdminAchievement(item.id, { name: item.name, description: item.description, icon: item.icon, conditionType: item.conditionType, conditionValue: item.conditionValue, isActive: Boolean(item.isActive) }); setNotice('บันทึก Achievement แล้ว'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'บันทึกไม่สำเร็จ'); } };

  return <div className="space-y-5 pb-8"><section className="relative overflow-hidden rounded-3xl border border-violet-300/15 bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 p-6 shadow-2xl sm:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl" /><div className="relative"><p className="font-mono text-[10px] font-bold tracking-[.2em] text-violet-300">ACHIEVEMENT MANAGEMENT</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">จัดการเหรียญเกียรติยศ</h1><p className="mt-2 text-sm text-slate-400">กำหนดเหรียญ เงื่อนไขการปลดล็อก และสถานะการแสดงผล</p></div></section>
    {(error || notice) && <div role="status" className={`rounded-2xl border p-3 text-sm ${error ? 'border-red-300/20 bg-red-400/10 text-red-300' : 'border-emerald-300/20 bg-emerald-400/10 text-emerald-300'}`}>{error || notice}</div>}
    <form onSubmit={async (e) => { e.preventDefault(); setError(''); try { await api.createAdminAchievement(form); setForm({ name: '', description: '', icon: 'Award', conditionType: 'mission_count', conditionValue: 1, isActive: true }); setNotice('สร้าง Achievement แล้ว'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'สร้างไม่สำเร็จ'); } }} className="grid gap-3 rounded-3xl border border-slate-700 bg-slate-900/60 p-5 md:grid-cols-2 xl:grid-cols-[1fr_1.5fr_150px_220px_100px_auto]"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="ชื่อ Achievement" className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /><input required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="คำอธิบาย" className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm" /><select value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value })} className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm">{iconOptions.map((icon) => <option key={icon}>{icon}</option>)}</select><select value={form.conditionType} onChange={(e) => setForm({ ...form, conditionType: e.target.value })} className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm">{conditionTypes.map((type) => <option key={type} value={type}>{conditionLabels[type] || type}</option>)}</select><input type="number" min={1} value={form.conditionValue} onChange={(e) => setForm({ ...form, conditionValue: Number(e.target.value) })} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 font-mono text-sm" /><button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-500 to-cyan-400 px-4 text-sm font-black text-slate-950"><Plus className="h-4 w-4" />สร้าง</button></form>
    <section className="grid gap-4 xl:grid-cols-2">{items.map((item) => <article key={item.id} className={`rounded-3xl border p-5 shadow-xl ${item.isActive ? 'border-violet-300/20 bg-slate-900/70' : 'border-slate-700 bg-slate-900/40 opacity-70'}`}><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl border border-violet-300/20 bg-gradient-to-br from-violet-500/20 to-cyan-400/10 text-violet-300"><Award className="h-6 w-6" /></div><div className="min-w-0 flex-1"><input value={item.name} onChange={(e) => mutate(item.id, { name: e.target.value })} className="h-10 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 font-bold" /><input value={item.description} onChange={(e) => mutate(item.id, { description: e.target.value })} className="mt-2 h-10 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 text-xs" /></div></div><div className="mt-4 grid gap-2 sm:grid-cols-[130px_1fr_90px]"><select value={item.icon} onChange={(e) => mutate(item.id, { icon: e.target.value })} className="h-10 rounded-xl border border-slate-700 bg-slate-950 px-2 text-xs">{iconOptions.map((icon) => <option key={icon}>{icon}</option>)}</select><select value={item.conditionType} onChange={(e) => mutate(item.id, { conditionType: e.target.value })} className="h-10 rounded-xl border border-slate-700 bg-slate-950 px-2 text-xs">{conditionTypes.map((type) => <option key={type} value={type}>{conditionLabels[type] || type}</option>)}</select><input type="number" min={1} value={item.conditionValue} onChange={(e) => mutate(item.id, { conditionValue: Number(e.target.value) })} className="h-10 rounded-xl border border-slate-700 bg-slate-950 px-2 font-mono text-xs" /></div><div className="mt-4 flex items-center gap-2 border-t border-slate-800 pt-4"><span className="inline-flex items-center gap-1 rounded-full bg-emerald-400/10 px-2.5 py-1 text-[10px] font-bold text-emerald-300"><Sparkles className="h-3 w-3" />ปลดล็อกแล้ว {item.unlockedCount}</span><label className="ml-auto flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={Boolean(item.isActive)} onChange={async (e) => { await api.setAdminAchievementActive(item.id, e.target.checked); await load(); }} />เปิดใช้งาน</label><button onClick={() => void save(item)} className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-400 text-slate-950"><Save className="h-4 w-4" /></button><button onClick={() => setDeleteTarget(item)} disabled={item.unlockedCount > 0} title={item.unlockedCount ? 'ปิดใช้งานแทน เนื่องจากมีผู้ได้รับแล้ว' : 'ลบ'} className="grid h-9 w-9 place-items-center rounded-xl border border-red-300/20 text-red-300 disabled:cursor-not-allowed disabled:opacity-30"><Trash2 className="h-4 w-4" /></button></div></article>)}</section>
    <div className="flex items-center gap-2 rounded-2xl border border-cyan-300/15 bg-cyan-400/[.05] p-4 text-xs text-slate-400"><ShieldCheck className="h-5 w-5 text-cyan-300" />Achievement ที่มีผู้ปลดล็อกแล้วจะลบไม่ได้ เพื่อรักษาประวัติของผู้เรียน แต่สามารถปิดใช้งานได้</div>
    <AdminConfirmationModal open={Boolean(deleteTarget)} title="ลบ Achievement?" description={`${deleteTarget?.name || ''} จะถูกลบถาวร`} confirmLabel="ลบ Achievement" destructive onClose={() => setDeleteTarget(null)} onConfirm={async () => { if (!deleteTarget) return; try { await api.deleteAdminAchievement(deleteTarget.id); setNotice('ลบ Achievement แล้ว'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'ลบไม่สำเร็จ'); throw cause; } }} />
  </div>;
};
