import React, { useEffect, useState } from 'react';
import { BarChart3, Clock3, FileBarChart, Lightbulb, RefreshCw, Target, Users } from 'lucide-react';
import { api } from '../../services/api';
import type { AdminReportOptions, AdminReportsData } from '../../types';

const panel = 'rounded-[20px] border border-slate-700/70 bg-[#111827]/90 p-5 shadow-[0_18px_50px_rgba(0,0,0,.2)]';
const input = 'h-11 w-full rounded-xl border border-slate-700 bg-[#080D18] px-3 text-sm text-slate-200 outline-none focus:border-cyan-400';
type ReportTab = 'users'|'missions'|'assessments'|'time'|'hints';

export const AdminReportsPage: React.FC = () => {
  const [options,setOptions] = useState<AdminReportOptions|null>(null);
  const [data,setData] = useState<AdminReportsData|null>(null);
  const [filters,setFilters] = useState({from:'',to:'',userId:'',missionId:'',category:''});
  const [tab,setTab] = useState<ReportTab>('users');
  const [loading,setLoading] = useState(true);
  const [error,setError] = useState('');
  const load = async (next=filters) => { setLoading(true); setError(''); try { const [report,choices]=await Promise.all([api.getAdminReports(next),options?Promise.resolve(options):api.getAdminReportOptions()]); setData(report);setOptions(choices); } catch(e){setError(e instanceof Error?e.message:'โหลดรายงานไม่สำเร็จ');} finally{setLoading(false);} };
  useEffect(()=>{void load();},[]);
  const reset=()=>{const cleared={from:'',to:'',userId:'',missionId:'',category:''};setFilters(cleared);void load(cleared);};
  const tabs: Array<[ReportTab,string]> = [['users','ความคืบหน้าผู้เรียน'],['missions','ประสิทธิภาพภารกิจ'],['assessments','ผลแบบประเมิน'],['time','เวลาเรียนจริง'],['hints','การใช้คำใบ้']];
  const empty=<tr><td colSpan={7} className="py-12 text-center text-sm text-slate-500">ไม่พบข้อมูลตามตัวกรอง</td></tr>;

  return <div className="space-y-6"><header className="rounded-[24px] border border-cyan-400/20 bg-gradient-to-br from-[#111C31] to-[#171229] p-6 sm:p-8"><div className="flex items-center gap-3 text-cyan-300"><FileBarChart className="h-6 w-6"/><span className="text-xs font-black tracking-[.2em]">ADMIN REPORTS</span></div><h1 className="mt-3 text-2xl font-black sm:text-3xl">รายงานการเรียนรู้</h1><p className="mt-2 text-sm text-slate-400">ข้อมูลจริงจากกิจกรรม ภารกิจ แบบประเมิน Active Learning Time และ Hint Usage</p></header>
    <section className={panel}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="text-xs font-bold text-slate-400">ตั้งแต่<input className={`${input} mt-2`} type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label className="text-xs font-bold text-slate-400">ถึง<input className={`${input} mt-2`} type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label className="text-xs font-bold text-slate-400">ผู้เรียน<select className={`${input} mt-2`} value={filters.userId} onChange={e=>setFilters({...filters,userId:e.target.value})}><option value="">ทั้งหมด</option>{options?.users.map(x=><option key={x.id} value={x.id}>{x.username}</option>)}</select></label><label className="text-xs font-bold text-slate-400">ภารกิจ<select className={`${input} mt-2`} value={filters.missionId} onChange={e=>setFilters({...filters,missionId:e.target.value})}><option value="">ทั้งหมด</option>{options?.missions.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label className="text-xs font-bold text-slate-400">หมวดหมู่<select className={`${input} mt-2`} value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">ทั้งหมด</option>{options?.categories.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="mt-4 flex gap-2"><button onClick={()=>void load()} className="rounded-xl bg-gradient-to-r from-cyan-400 to-blue-500 px-5 py-2.5 text-sm font-black text-slate-950">ใช้ตัวกรอง</button><button onClick={reset} className="rounded-xl border border-slate-700 px-4 py-2.5 text-sm font-bold text-slate-300">ล้างตัวกรอง</button></div>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}</section>
    {data&&<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[
      ['ผู้เรียน',data.summary.learners,Users,'text-cyan-300'],['สำเร็จภารกิจ',`${data.summary.missionCompletionRate}%`,Target,'text-emerald-300'],['Assessment',data.summary.assessmentSubmissions,BarChart3,'text-violet-300'],['Active Time',`${Math.round(data.summary.activeLearningSeconds/60)} นาที`,Clock3,'text-amber-300'],['Hint Usage',data.summary.hintsUsed,Lightbulb,'text-orange-300']
    ].map(([label,value,Icon,color]:any)=><article key={label} className="rounded-2xl border border-slate-700/70 bg-[#111827] p-5"><div className="flex justify-between text-sm text-slate-400"><span>{label}</span><Icon className={`h-5 w-5 ${color}`}/></div><p className="mt-3 font-mono text-2xl font-black">{value}</p></article>)}</section>
    <section className={panel}><div className="flex gap-2 overflow-x-auto pb-2">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold ${tab===key?'bg-cyan-400 text-slate-950':'bg-slate-800 text-slate-400'}`}>{label}</button>)}</div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm">
      {tab==='users'&&<><thead><tr className="border-b border-slate-700 text-slate-500"><th className="p-3">ผู้เรียน</th><th className="p-3">Touched</th><th className="p-3">Started</th><th className="p-3">Completed</th><th className="p-3">Completion Rate</th></tr></thead><tbody>{data.userProgress.length?data.userProgress.map(x=><tr key={x.userId} className="border-b border-slate-800"><td className="p-3 font-bold">{x.username}</td><td className="p-3 font-mono">{x.missionsTouched}</td><td className="p-3 font-mono">{x.missionsStarted}</td><td className="p-3 font-mono text-emerald-300">{x.missionsCompleted}</td><td className="p-3 font-mono">{x.completionRate}%</td></tr>):empty}</tbody></>}
      {tab==='missions'&&<><thead><tr className="border-b border-slate-700 text-slate-500"><th className="p-3">ภารกิจ</th><th className="p-3">หมวดหมู่</th><th className="p-3">ผู้เรียน</th><th className="p-3">Started</th><th className="p-3">Completed</th><th className="p-3">Completion Rate</th></tr></thead><tbody>{data.missionPerformance.length?data.missionPerformance.map(x=><tr key={x.missionId} className="border-b border-slate-800"><td className="p-3 font-bold">{x.title}</td><td className="p-3 text-slate-400">{x.category}</td><td className="p-3 font-mono">{x.learners}</td><td className="p-3 font-mono">{x.started}</td><td className="p-3 font-mono text-emerald-300">{x.completed}</td><td className="p-3 font-mono">{x.completionRate}%</td></tr>):empty}</tbody></>}
      {tab==='assessments'&&<><thead><tr className="border-b border-slate-700 text-slate-500"><th className="p-3">ประเภท</th><th className="p-3">Submissions</th><th className="p-3">Participants</th><th className="p-3">Average</th><th className="p-3">Min</th><th className="p-3">Max</th></tr></thead><tbody>{data.assessmentPerformance.length?data.assessmentPerformance.map(x=><tr key={x.assessmentType} className="border-b border-slate-800"><td className="p-3 font-bold uppercase">{x.assessmentType}</td><td className="p-3 font-mono">{x.submissions}</td><td className="p-3 font-mono">{x.participants}</td><td className="p-3 font-mono text-cyan-300">{x.averageScore}%</td><td className="p-3 font-mono">{x.minimumScore}%</td><td className="p-3 font-mono">{x.maximumScore}%</td></tr>):empty}</tbody></>}
      {tab==='time'&&<><thead><tr className="border-b border-slate-700 text-slate-500"><th className="p-3">ผู้เรียน</th><th className="p-3">Active Learning Time</th><th className="p-3">Sessions</th><th className="p-3">Average Session</th></tr></thead><tbody>{data.activeLearningTime.length?data.activeLearningTime.map(x=><tr key={x.userId} className="border-b border-slate-800"><td className="p-3 font-bold">{x.username}</td><td className="p-3 font-mono text-amber-300">{Math.round(x.activeSeconds/60)} นาที</td><td className="p-3 font-mono">{x.sessions}</td><td className="p-3 font-mono">{Math.round(x.averageSessionSeconds/60)} นาที</td></tr>):empty}</tbody></>}
      {tab==='hints'&&<><thead><tr className="border-b border-slate-700 text-slate-500"><th className="p-3">ภารกิจ</th><th className="p-3">หมวดหมู่</th><th className="p-3">Hint Used</th><th className="p-3">ผู้เรียน</th></tr></thead><tbody>{data.hintUsage.length?data.hintUsage.map(x=><tr key={x.missionId} className="border-b border-slate-800"><td className="p-3 font-bold">{x.title}</td><td className="p-3 text-slate-400">{x.category}</td><td className="p-3 font-mono text-orange-300">{x.hintsUsed}</td><td className="p-3 font-mono">{x.learners}</td></tr>):empty}</tbody></>}
    </table></div>{loading&&<div className="mt-4 flex items-center gap-2 text-sm text-cyan-300"><RefreshCw className="h-4 w-4 animate-spin"/>กำลังอัปเดตข้อมูล</div>}</section></>}
  </div>;
};
