import React, { useEffect, useState } from 'react';
import { ArrowLeft, Edit3, Eye, EyeOff, GripVertical, Plus, Save, Trash2, MoveDown, MoveUp } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { AdminConfirmationModal } from '../../components/admin/AdminConfirmationModal';
import { api } from '../../services/api';
import type { AdminMission, AdminMissionDifficulty, AdminMissionStatus, AdminMissionTask, AdminMissionTaskType } from '../../types';

const categories = ['Network Fundamentals', 'IP Addressing', 'Switching', 'VLAN', 'Routing', 'Troubleshooting', 'Security'];
const taskTypeLabels: Record<AdminMissionTaskType, string> = { scenario: 'Scenario', diagram: 'Network Diagram', lab: 'Packet Tracer Lab', investigation: 'Investigation', questions: 'Questions', flag: 'Capture the Flag' };
const emptyTask = { taskType: 'scenario' as AdminMissionTaskType, title: '', content: '', isEnabled: 1 };

type MissionForm = Omit<AdminMission, 'id' | 'createdAt' | 'updatedAt' | 'taskCount'>;
const initialForm: MissionForm = { missionNumber: 1, title: '', slug: '', description: '', scenario: '', category: 'Network Fundamentals', difficulty: 'easy', estimatedMinutes: 20, xpReward: 100, coinReward: 500, flag: 'FLAG{}', status: 'draft', orderIndex: 1, learningPathId: null, packetTracerFile: '' };

export const AdminMissionEditorPage: React.FC = () => {
  const navigate = useNavigate(); const params = useParams(); const editingId = params.id ? Number(params.id) : null;
  const [form, setForm] = useState<MissionForm>(initialForm); const [tasks, setTasks] = useState<AdminMissionTask[]>([]);
  const [taskDraft, setTaskDraft] = useState(emptyTask); const [editingTaskId, setEditingTaskId] = useState<number | null>(null);
  const [loading, setLoading] = useState(Boolean(editingId)); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [deleteTask, setDeleteTask] = useState<AdminMissionTask | null>(null);

  const loadMission = async (id: number) => { setLoading(true); try { const result = await api.getAdminMission(id); const { id: _id, createdAt: _created, updatedAt: _updated, taskCount: _count, ...missionForm } = result.mission; setForm(missionForm); setTasks(result.tasks); } catch (e) { setError(e instanceof Error ? e.message : 'โหลดภารกิจไม่สำเร็จ'); } finally { setLoading(false); } };
  useEffect(() => { if (editingId) void loadMission(editingId); else void api.getAdminMissions({ page: 1, pageSize: 100, search: '', category: 'all', difficulty: 'all', status: 'all', sortBy: 'orderIndex', sortOrder: 'desc' }).then((result) => { const maxNumber = Math.max(0, ...result.missions.map((m) => m.missionNumber)); const maxOrder = Math.max(0, ...result.missions.map((m) => m.orderIndex)); setForm((current) => ({ ...current, missionNumber: maxNumber + 1, orderIndex: maxOrder + 1, slug: `mission-${maxNumber + 1}` })); }); }, [editingId]);
  const set = <K extends keyof MissionForm>(key: K, value: MissionForm[K]) => setForm((current) => ({ ...current, [key]: value }));

  const saveMission = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setNotice(''); try { if (editingId) { await api.updateAdminMission(editingId, form); setNotice('บันทึกภารกิจแล้ว'); await loadMission(editingId); } else { const result = await api.createAdminMission(form); navigate(`/admin/missions/${result.mission.id}/edit`, { replace: true }); } } catch (e) { setError(e instanceof Error ? e.message : 'บันทึกไม่สำเร็จ'); } finally { setSaving(false); } };
  const saveTask = async () => { if (!editingId || !taskDraft.title.trim()) return; setError(''); try { if (editingTaskId) await api.updateAdminMissionTask(editingId, editingTaskId, taskDraft); else await api.createAdminMissionTask(editingId, taskDraft); setTaskDraft(emptyTask); setEditingTaskId(null); await loadMission(editingId); setNotice('บันทึก Task แล้ว'); } catch (e) { setError(e instanceof Error ? e.message : 'บันทึก Task ไม่สำเร็จ'); } };
  const editTask = (task: AdminMissionTask) => { setEditingTaskId(task.id); setTaskDraft({ taskType: task.taskType, title: task.title, content: task.content, isEnabled: task.isEnabled }); };

  if (loading) return <div className="py-20 text-center text-slate-500">กำลังโหลดภารกิจ...</div>;
  const input = 'mt-2 h-11 w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 text-sm text-white outline-none focus:border-cyan-400';
  return <div className="space-y-6 pb-8"><button onClick={() => navigate('/admin/missions')} className="inline-flex items-center gap-2 text-sm font-bold text-slate-400 hover:text-cyan-300"><ArrowLeft className="h-4 w-4" />กลับหน้าภารกิจ</button>
    <section className="rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-slate-800/95 to-slate-950 p-6 shadow-2xl sm:p-8"><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">MISSION EDITOR</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">{editingId ? 'แก้ไขภารกิจ' : 'สร้างภารกิจใหม่'}</h2><p className="mt-2 text-sm text-slate-400">แก้ไขข้อมูลในระบบ Mission เดิม การเปลี่ยนแปลงที่ Published จะแสดงในหน้า User</p></section>
    {(error || notice) && <p className={`rounded-2xl border p-4 text-sm ${error ? 'border-red-400/20 bg-red-400/10 text-red-300' : 'border-emerald-400/20 bg-emerald-400/10 text-emerald-300'}`}>{error || notice}</p>}
    <form onSubmit={saveMission} className="rounded-3xl border border-slate-700/60 bg-slate-900/65 p-5 shadow-xl sm:p-6"><div className="flex items-center justify-between"><div><h3 className="text-lg font-black">ข้อมูลภารกิจ</h3><p className="mt-1 text-xs text-slate-500">Flag แสดงเฉพาะ Admin และผู้เรียนที่ทำภารกิจสำเร็จแล้ว</p></div><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-black text-slate-950 disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'กำลังบันทึก...' : 'บันทึก'}</button></div>
      <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-bold text-slate-400">Mission Number<input type="number" min="1" required value={form.missionNumber} onChange={(e) => set('missionNumber', Number(e.target.value))} className={input} /></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Title<input required value={form.title} onChange={(e) => { set('title', e.target.value); if (!editingId) set('slug', e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); }} className={input} /></label><label className="text-xs font-bold text-slate-400">Slug<input required value={form.slug} onChange={(e) => set('slug', e.target.value)} className={input} /></label><label className="text-xs font-bold text-slate-400 md:col-span-2 xl:col-span-4">Description<textarea required value={form.description} onChange={(e) => set('description', e.target.value)} className={`${input} h-24 py-3`} /></label><label className="text-xs font-bold text-slate-400 md:col-span-2 xl:col-span-4">Scenario<textarea required value={form.scenario} onChange={(e) => set('scenario', e.target.value)} className={`${input} h-36 py-3`} /></label>
        <label className="text-xs font-bold text-slate-400">Category<select value={form.category} onChange={(e) => set('category', e.target.value)} className={input}>{categories.map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-xs font-bold text-slate-400">Difficulty<select value={form.difficulty} onChange={(e) => set('difficulty', e.target.value as AdminMissionDifficulty)} className={input}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label className="text-xs font-bold text-slate-400">Status<select value={form.status} onChange={(e) => set('status', e.target.value as AdminMissionStatus)} className={input}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="text-xs font-bold text-slate-400">Estimated Minutes<input type="number" min="1" value={form.estimatedMinutes} onChange={(e) => set('estimatedMinutes', Number(e.target.value))} className={input} /></label><label className="text-xs font-bold text-slate-400">XP Reward<input type="number" min="0" value={form.xpReward} onChange={(e) => set('xpReward', Number(e.target.value))} className={input} /></label><label className="text-xs font-bold text-slate-400">Coin Reward<input type="number" min="0" value={form.coinReward} onChange={(e) => set('coinReward', Number(e.target.value))} className={input} /></label><label className="text-xs font-bold text-slate-400">Order Index<input type="number" min="1" value={form.orderIndex} onChange={(e) => set('orderIndex', Number(e.target.value))} className={input} /></label><label className="text-xs font-bold text-slate-400">Learning Path ID<input type="number" min="1" value={form.learningPathId ?? ''} onChange={(e) => set('learningPathId', e.target.value ? Number(e.target.value) : null)} className={input} /></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Packet Tracer File<input value={form.packetTracerFile} onChange={(e) => set('packetTracerFile', e.target.value)} placeholder="mission_lab.pka" className={input} /></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Flag<input required value={form.flag} onChange={(e) => set('flag', e.target.value)} className={`${input} font-mono text-rose-300`} /></label>
      </div></form>

    <section className="rounded-3xl border border-slate-700/60 bg-slate-900/65 p-5 shadow-xl sm:p-6"><div className="flex items-center justify-between"><div><h3 className="text-lg font-black">Mission Tasks</h3><p className="mt-1 text-xs text-slate-500">เพิ่ม แก้ไข เปิด/ปิด และจัดลำดับ Task ที่แสดงใน Mission Room</p></div><span className="font-mono text-xs text-violet-300">{tasks.length} TASKS</span></div>
      {!editingId ? <div className="mt-6 rounded-2xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">บันทึกภารกิจก่อนจึงจะเพิ่ม Task ได้</div> : <><div className="mt-6 space-y-2">{tasks.map((task) => <div key={task.id} className={`flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center ${task.isEnabled ? 'border-slate-700 bg-slate-950/40' : 'border-slate-800 bg-slate-950/20 opacity-60'}`}><GripVertical className="hidden h-5 w-5 text-slate-600 sm:block" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-violet-400/10 px-2 py-1 font-mono text-[9px] font-bold text-violet-300">{taskTypeLabels[task.taskType]}</span><span className="font-mono text-[10px] text-slate-600">ORDER {task.orderIndex}</span></div><p className="mt-2 truncate text-sm font-bold text-slate-200">{task.title}</p><p className="mt-1 line-clamp-1 text-xs text-slate-500">{task.content || 'ไม่มีรายละเอียดเพิ่มเติม'}</p></div><div className="flex gap-1.5"><button type="button" onClick={async () => { await api.reorderAdminMissionTask(editingId, task.id, 'up'); await loadMission(editingId); }} className="rounded-lg border border-slate-700 p-2"><MoveUp className="h-3.5 w-3.5" /></button><button type="button" onClick={async () => { await api.reorderAdminMissionTask(editingId, task.id, 'down'); await loadMission(editingId); }} className="rounded-lg border border-slate-700 p-2"><MoveDown className="h-3.5 w-3.5" /></button><button type="button" onClick={async () => { await api.setAdminMissionTaskEnabled(editingId, task.id, !Boolean(task.isEnabled)); await loadMission(editingId); }} className={`rounded-lg border p-2 ${task.isEnabled ? 'border-emerald-300/20 text-emerald-300' : 'border-slate-700 text-slate-500'}`}>{task.isEnabled ? <Eye className="h-3.5 w-3.5" /> : <EyeOff className="h-3.5 w-3.5" />}</button><button type="button" onClick={() => editTask(task)} className="rounded-lg border border-cyan-300/20 p-2 text-cyan-300"><Edit3 className="h-3.5 w-3.5" /></button><button type="button" onClick={() => setDeleteTask(task)} className="rounded-lg border border-red-300/20 p-2 text-red-300"><Trash2 className="h-3.5 w-3.5" /></button></div></div>)}</div>
        <div className="mt-5 rounded-2xl border border-slate-700 bg-slate-950/40 p-4"><h4 className="font-bold text-slate-200">{editingTaskId ? 'แก้ไข Task' : 'เพิ่ม Task'}</h4><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-xs font-bold text-slate-400">Task Type<select value={taskDraft.taskType} onChange={(e) => setTaskDraft((v) => ({ ...v, taskType: e.target.value as AdminMissionTaskType }))} className={input}>{Object.entries(taskTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-bold text-slate-400">Title<input value={taskDraft.title} onChange={(e) => setTaskDraft((v) => ({ ...v, title: e.target.value }))} className={input} /></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Content<textarea value={taskDraft.content} onChange={(e) => setTaskDraft((v) => ({ ...v, content: e.target.value }))} className={`${input} h-28 py-3`} /></label><label className="flex items-center gap-2 text-xs font-bold text-slate-400"><input type="checkbox" checked={Boolean(taskDraft.isEnabled)} onChange={(e) => setTaskDraft((v) => ({ ...v, isEnabled: e.target.checked ? 1 : 0 }))} />เปิดใช้งาน Task</label></div><div className="mt-4 flex justify-end gap-2">{editingTaskId && <button type="button" onClick={() => { setEditingTaskId(null); setTaskDraft(emptyTask); }} className="rounded-xl border border-slate-700 px-4 py-2 text-xs font-bold">ยกเลิก</button>}<button type="button" onClick={() => void saveTask()} className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-2 text-xs font-black"><Plus className="h-4 w-4" />{editingTaskId ? 'บันทึก Task' : 'เพิ่ม Task'}</button></div></div></>}
    </section>
    <AdminConfirmationModal open={Boolean(deleteTask)} title="ลบ Task?" description={`Task “${deleteTask?.title || ''}” จะถูกลบออกจาก Mission Room`} confirmLabel="ลบ Task" destructive onClose={() => setDeleteTask(null)} onConfirm={async () => { if (editingId && deleteTask) { await api.deleteAdminMissionTask(editingId, deleteTask.id); await loadMission(editingId); } }} />
  </div>;
};
